[package]
name = "rustbus-service-macros"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.0"
quote = "1.0"
syn = "2.0"
